# Generated by Django 3.1.6 on 2021-02-12 03:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20210126_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='count_field',
            new_name='total_pop',
        ),
        migrations.RemoveField(
            model_name='county',
            name='objectid',
        ),
        migrations.RemoveField(
            model_name='county',
            name='unit_area',
        ),
        migrations.RemoveField(
            model_name='county',
            name='unit_perim',
        ),
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
