# Generated by Django 3.1.6 on 2021-02-16 20:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_lodge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(max_length=120)),
                ('iso3', models.CharField(max_length=3)),
                ('gisname', models.CharField(max_length=80)),
                ('site_code', models.IntegerField()),
                ('area_sqkm_field', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
